services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: alura
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: alura_store
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres_network
    user: "999:999"

networks:
  postgres_network:
    driver: bridge

volumes:
  data:
    driver: local
